### ISSUE TITLE
Unclear Instructions 

### ISSUE THREAD

**Issue by arey0pushpa** [derekelkins/agda-vim#10]
Can you provide better instruction to use this  :
  
After copying all files to the .vim folder add to filetypes.vim.
au BufNewFile,BufRead *.agda setf agda

This Link (http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Main.VIMEditing
)  says add to filetype.agda

filetype ?? filetypes ??

I have gone for automatic loading of syntax  .

Error detected while processing /home/mokambo/.vim/syntax/agda.vim:
line    8:
E127: Cannot redefine function ReloadSyntax: It is in use
E127: Cannot redefine function ReloadSyntax: It is in use
E127: Cannot redefine function ReloadSyntax: It is in use
E127: Cannot redefine function ReloadSyntax: It is in use
E127: Cannot redefine function ReloadSyntax: It is in use
E127: Cannot redefine function ReloadSyntax: It is in use
E127: Cannot redefine function ReloadSyntax: It is in use

agda.vim :

function! ReloadSyntax()
  syntax clear
  runtime syntax/agda.vim
  let f = expand('%:h') . "/." . expand('%:t') . ".vim"
  if filereadable(f)
    exec "source " . escape(f, '*')
  endif
endfunction

call ReloadSyntax()

map ,rs :call ReloadSyntax()<CR>

Thanks.

**Comment by derekelkins** [comment]
I made some tweaks to the README.  You don't need any of the files or code snippets from the VIMEditing wiki page (and you should probably delete them if you had them from before).  I'd recommend using a vim bundling solution such as [Pathogen](https://github.com/tpope/vim-pathogen).  At that point you should only need to `git clone` the repository into the bundle folder.
