### ISSUE TITLE
Cannot resize buffers with C-w =

### ISSUE THREAD

**Issue by nkaretnikov** [derekelkins/agda-vim#14]
VIM - Vi IMproved 7.4

The special agda-vim buffers (where errors are shown, etc.) are not affected by `C-w =`, so I need to do `C-w o` followed by `, l` to resize them, which is very inconvenient.

**Comment by derekelkins** [comment]
This is just the default behavior of the QuickFix window.  It has the option `'winfixheight'` set by default.  You can add something like `autocmd FileType qf set nowinfixheight` to work around this behavior.
