### ISSUE TITLE
Support Agda 2.6.0

### ISSUE THREAD

**Issue by nkaretnikov** [derekelkins/agda-vim#16]
FWIW, I've tried 2.6.0 from upstream, but agda-vim gives me
```
Error: Choose at most one: input file or --interaction.
```
Note that I'm on a weird system (https://github.com/NixOS/nixpkgs/issues/15617), so it might work differently somewhere else.

**Comment by derekelkins** [comment]
Thanks for bringing this to my attention.  They changed the way the `Cmd_load` is interpreted so it was definitely doing the wrong thing in 2.5.0+.  I pushed a change that should resolve this. Tell me if you still have troubles.  It didn't look like they changed anything else about the interactive interface.

**Comment by nkaretnikov** [comment]
@derekelkins Thanks for the quick response! I'm a bit busy right now but should be able to take a look in a couple of days. Feel free to ping me if I forget.

P.S. Finished reading your "Understanding typing judgments" article today. What a great read! Hope you won't abandon the blog. ;)

**Comment by derekelkins** [comment]
Closing because I think this is fixed.  Comment if you're still having trouble.

**Comment by nkaretnikov** [comment]
I got distracted by other things, so don't hold your breath. ;) Thanks!
