### ISSUE TITLE
Normalize broken for Agda 2.5.3

### ISSUE THREAD

**Issue by kellino** [derekelkins/agda-vim#30]
The Normalise() function seems to be broken for Agda 2.5.3. 

I've temporarily fixed this by changing the version number in line 459 (ftplugin/agda.vim) to

```python
if compareVersion([2,5,3,0], agdaVersion, operators.lt):
```
This seems too small for a pull request, and might not be the best solution, so I've stuck it here.

**Comment by derekelkins** [comment]
The logic was inverted. It should be fixed now.
