### ISSUE TITLE
Error: First load the file.

### ISSUE THREAD

**Issue by MaiaVictor** [derekelkins/agda-vim#33]
I've installed agda-vim by cloning the repository to `~/.vim/bundle`. I've also edited `.vim/filetypes.vim` and `.vimrc` as explained on the README. When I open an Agda file, it seems to recognize the extension: I'm able to type special characters and call the commands. But when I press, for example, `,t`, and then enter an expression (such as `ℕ`), I get the following error: `Error: First load the file.`. I'm using the following file:

```agda
module Hello where

  data ℕ : Set where
    zero : ℕ
    suc : ℕ → ℕ

  _+_ : ℕ → ℕ → ℕ
  zero + m = m
  (suc n) + m = suc (n + m)

```

What does that mean?

**Comment by derekelkins** [comment]
If Agda fails to load the file then almost none of the commands will be able to do anything meaningful. `:cwindow` should show any errors, or you can use `:make` to attempt to compile the Agda file, and it will show you the output. My guess is that you don't have this in a file named `Hello.agda` as Agda requires module names to match file names.

**Comment by MaiaVictor** [comment]
@derekelkins, I indeed have it in a file named `Hello.agda`. `:make`  outputs:

```
Loading  Hello (/Users/v/vic/dev/agda/Hello.agdai).

Press ENTER or type command to continue
```

Perhaps it is my Agda version? I have:  `Agda version 2.5.3-e3f5983-dirty`. Using `:make` after `:cwindow` outputs:

```
Error detected while processing function AgdaVersion:
line    4:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<string>", line 162, in sendCommand
  File "<string>", line 99, in interpretResponse
  File "<string>", line 90, in parseVersion
ValueError: invalid literal for int() with base 10: '3-e3f5983-dirty'
```

So that seems to be indeed the case... I'll reinstall Agda now.
