### ISSUE TITLE
agda stdlib permission errors

### ISSUE THREAD

**Issue by sanderr** [derekelkins/agda-vim#38]
agda-vim appears to be trying to open stdlib files in the same way it does other source files. This means it tries to create .SomeLibrary.agda.vim files in a priviliged directory.
A line `open import Data.Nat` results in the below error:

`/usr/share/agda/lib/stdlib/Data/Nat/Base.agda|9 col 8 error|  /usr/share/agda/lib/stdlib/.Level.agda.vim: openFile: permission denied (Permission denied)`

**Comment by louisswarren** [comment]
This issue can be caused by agda trying to generate the `.agdai` file for a standard library file, due to it not being generated when the standard library was installed. Are you able to run agda directly on your test file? I.e. if you put `open import Data.Nat` in `test.agda`, can you run `agda test.agda` with no errors?

**Comment by sanderr** [comment]
I can not. This results in
```
 Checking Data.Nat (/usr/share/agda/lib/stdlib/Data/Nat.agda).
  Checking Data.Nat.Base (/usr/share/agda/lib/stdlib/Data/Nat/Base.agda).
   Checking Level (/usr/share/agda/lib/stdlib/Level.agda).
Failed to write interface /usr/share/agda/lib/stdlib/Level.agdai.
/usr/share/agda/lib/stdlib/Data/Nat/Base.agda:9,8-13
/usr/share/agda/lib/stdlib/Level.agdai: removeLink: permission
denied (Permission denied
```

I assume this means that my issue has nothing to do with agda-vim? `/usr/share/agda/` has 750 permissions for directories and 640 for files, with owner `root:root`, so I understand why agda (when run as a non-elevated user) has no permission, but I do not understand why it needs this permission? Libraries are only meant for reading, no?

**Comment by sanderr** [comment]
Obviously, I meant 755 and 644 permissions.

**Comment by sanderr** [comment]
It appears to be an issue with my setup. I had installed agda via stack, and now tried agda from the arch repo's. This resolved my issue. Thanks for the help.
