### ISSUE TITLE
Filename not matching module name leads to obscure errors

### ISSUE THREAD

**Issue by blakej11** [derekelkins/agda-vim#54]
I was following the example from your demonstration video (https://youtu.be/i7Btts-duZw?t=96). As my very first attempt to use this plugin, I entered the following text into a file:

```
module demo1A where

data Bool : Set where
  True : Bool
  False : Bool

if_then_else_ : {A : Set} → Bool → A → A → A
if b then t else e = ?
```

I reloaded Agda via `\l`, navigated my cursor to the `?`, and typed `\c`. This gave me a `Goal not loaded` error. I tried a few other commands (`\a`, `\r`, `\t`) and they all failed with the same error. I was going to give up and assume that the passage of time had caused it to break, but on a whim I tried renaming the file from `try.agda` to `demo1A.agda` ... and then it worked.

Since I'm just starting to learn Agda, I didn't know about any assumptions it might make regarding mappings between module names and file names (but I guess I do now!) It would be nice if this plugin would give a more useful error message in the case of this kind of failure.

**Comment by derekelkins** [comment]
When I do it, the quickfix window pops up with the error messages from Agda, which in this case is: "The name of the top level module does not match the file name. [...]" You can manually show the quickfix window via `:cwindow`. You could also use `:make` or `:AgdaLoad` both of which will display the output of running Agda. (For diagnostic purposes, worst-case, you could have just run Agda yourself from the command line.)

I have:

```vim
" Automatically pop open the quickfix window if there are errors (and close if there are none).
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost l* nested lwindow
autocmd BufReadPost quickfix set nobuflisted
```

in my `.vimrc`, though even when commented out the behavior was the same. I believe `:make` will also lead to the quickfix window being opened if there are errors (or holes), and this is demonstrated near the end of the video. In fact, I'm not really sure how to get the behavior you describe, i.e. no quickfix window popping up, short of doing something to explicitly suppress the quickfix window.
