### ISSUE TITLE
Python plugin

### ISSUE THREAD

**Issue by david-christiansen** [derekelkins/agda-vim#7]
Sorry to be communicating through an issue, but I haven't been able to find another way to get ahold of you. I'm one of the developers of Idris, which has just gotten support for Agda-style semantic highlighting. I'd like to help the authors of the vim mode for Idris support semantic highlighting like you have for Agda, but I can't seem to find the Python code that does the highlighting.

Would it be possible to put it in the repo or link to it? Or am I just overseeing the code?

**Comment by derekelkins** [comment]
The ReloadSyntax vim function handles loading files produced by "agda --vim", namely files with names like .MyAgdaFile.agda.vim.  The ReloadSyntax function is at the top of https://github.com/derekelkins/agda-vim/blob/master/ftplugin/agda.vim

**Comment by david-christiansen** [comment]
Thanks!
