### ISSUE TITLE
Goal not loaded when {! !} in comments.

### ISSUE THREAD

**Issue by JackeLee** [derekelkins/agda-vim#9]
In the code:
```agda
{-
{! !}
-}

id : ∀ {A : Set} → A → A
id = ?
```
If I try to refine or autocomplete `?` (with `<LocalLeader>r` or `<LocalLeader>a`) I get "Goal not loaded".

(By the way, thanks for this mode. It's awesome!)

**Comment by derekelkins** [comment]
Should be fixed, though a real fix would be adding appropriate syncing rules to the syntax file.
